### ISSUE TITLE
Common generic names for medications are not detected.

### ISSUE THREAD

**Issue by andydish** [fastdatascience/drug_named_entity_recognition#3]
First, I want to say this is an awesome project and has made some of my own work easier. Second, the package seems to have issues with generic names of very common medications such as Amphetamines/Adderall or Acetylsalicylic acid/Aspirin. For example:

`drug_test = find_drugs('aspirin'.split())
print(drug_test)`

Yields:

`[({'name': 'Aspirin', 'synonyms': {'Ecotrin', 'Acylpyrin', 'Acetysal', 'Easprin', 'Aspirtab', 'Colfarit', 'Entaprin', 'Aspirin', 'Valomag', 'Magnecyl', 'Fasprin', 'Buffex', 'Halfprin', 'Polopirin', 'Endosprin', 'Acuprin', 'Aloxiprimum', 'Aspidrox', 'Solupsan', 'Ascriptin', 'Miniprin', 'Dispril', 'Bayer', 'Solprin', 'Zorprin', 'Polopiryna', 'Ridiprin', 'Micristin'}, 'medline_plus_id': 'a621021', 'wikipedia_url': 'https://en.wikipedia.org/wiki/Aspirin', 'mesh_id': 'D058633'}, 0, 0)]
`

But has no mention of acetylsalicylic acid. In fact the inverse:

`drug_test = find_drugs('acetylsalicylic acid'.split())
print(drug_test)`

Yields:

`[]`

In DrugBank vocabulary Aspirin is a synonym for acetylsalicylic acid. There are others like valproic acid as well. Any idea what is causing this unexpected behavior?

Thanks again for the hard work on the package.

**Comment by woodthom2** [comment]
Thanks! I'll look into this and see if I can find a solution. In the meantime, do you have any idea what's going wrong?

**Comment by woodthom2** [comment]
Also, did you check that the generic name that is not matching, is in the DB?

**Comment by andydish** [comment]
Sure did. I ended up writing a script to make a new DB from the DrugBank one to solve the issue and it worked.

**Comment by woodthom2** [comment]
"acetylsalicylic acid" is now working in v2.0.0 of library (not yet on Pypi)
